"""customer auth session foundation

Revision ID: 847937edd08e
Revises: 36e752113d5e
Create Date: 2026-08-11 17:09:34.196592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '847937edd08e'
down_revision: Union[str, None] = '36e752113d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



class BrowserSessionMigrationPrecondition(RuntimeError):
    """Raised when pre-existing browser_session rows block this migration."""


def _require_empty_browser_session() -> None:
    """Refuse to proceed if any browser_session row already exists.

    `session_token_hash` is NOT NULL and CANNOT be backfilled: the verifier is
    derived from a bearer token that exists only in the customer's browser, so
    there is nothing on the server to compute it from.

    That leaves exactly three options for a pre-existing row, and two of them
    are unacceptable:

      - invent a hash  -> fabricates a credential nobody holds; the row would
                          look like a valid session that can never authenticate.
      - delete it      -> silently logs a real customer out with no operator
                          decision, no notice, and no record.
      - refuse         -> the operator decides, with a deliberate session
                          invalidation / maintenance plan.

    The expected state is zero rows: the customer schema has never been
    deployed. If that assumption is ever false, this migration stops rather
    than guessing.
    """
    connection = op.get_bind()
    existing = connection.execute(
        sa.text("SELECT count(*) FROM browser_session")
    ).scalar_one()
    if existing:
        raise BrowserSessionMigrationPrecondition(
            "MIGRATION PRECONDITION FAILED: {0} browser_session row(s) exist. "
            "Revision 847937edd08e adds session_token_hash NOT NULL, which "
            "cannot be backfilled because the token lives only in the "
            "customer's browser. This migration will not delete or fabricate "
            "sessions. Resolve deliberately with an explicit session "
            "invalidation plan (revoke and clear browser_session under "
            "operator authorization, notifying affected customers that they "
            "must sign in again), then re-run.".format(existing)
        )

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('code_salt', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempt_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms')", name=op.f('ck_auth_challenge_channel_valid')),
    sa.CheckConstraint("purpose IN ('login', 'step_up', 'email_ownership', 'phone_ownership', 'account_recovery')", name=op.f('ck_auth_challenge_purpose_valid')),
    sa.CheckConstraint("status <> 'consumed' OR (verified_at IS NOT NULL AND consumed_at IS NOT NULL)", name=op.f('ck_auth_challenge_consumed_after_verified')),
    sa.CheckConstraint("status <> 'locked' OR locked_at IS NOT NULL", name=op.f('ck_auth_challenge_locked_at_present')),
    sa.CheckConstraint("status <> 'verified' OR verified_at IS NOT NULL", name=op.f('ck_auth_challenge_verified_at_present')),
    sa.CheckConstraint("status IN ('pending', 'verified', 'consumed', 'expired', 'locked')", name=op.f('ck_auth_challenge_status_valid')),
    sa.CheckConstraint('attempt_count >= 0 AND attempt_count <= max_attempts', name=op.f('ck_auth_challenge_attempt_count_within_limit')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_challenge_expiry_after_creation')),
    sa.CheckConstraint('max_attempts >= 1', name=op.f('ck_auth_challenge_max_attempts_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_auth_challenge_account_id_customer_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_challenge'))
    )
    op.create_index('ix_auth_challenge_account_id', 'auth_challenge', ['account_id'], unique=False)
    op.create_index('ix_auth_challenge_expires_at', 'auth_challenge', ['expires_at'], unique=False)
    op.create_index('uq_auth_challenge_pending_target_purpose', 'auth_challenge', ['target', 'purpose'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('identity_verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=False),
    sa.Column('idv_stable_key', sa.String(length=255), nullable=True),
    sa.Column('adult_verified', sa.Boolean(), nullable=True),
    sa.Column('mobile_e164', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mobile_e164 IS NULL OR mobile_e164 ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f('ck_identity_verification_mobile_e164_format')),
    sa.CheckConstraint("purpose IN ('signup', 'phone_change', 'account_recovery', 'withdrawal')", name=op.f('ck_identity_verification_purpose_valid')),
    sa.CheckConstraint("status <> 'age_not_eligible' OR adult_verified IS FALSE", name=op.f('ck_identity_verification_age_not_eligible_is_not_adult')),
    sa.CheckConstraint("status <> 'verified' OR ( idv_stable_key IS NOT NULL AND adult_verified IS TRUE AND completed_at IS NOT NULL)", name=op.f('ck_identity_verification_verified_requires_adult_and_stable_key')),
    sa.CheckConstraint("status IN ('pending', 'verified', 'failed', 'age_not_eligible')", name=op.f('ck_identity_verification_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_identity_verification_account_id_customer_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person_identity.id'], name=op.f('fk_identity_verification_person_id_person_identity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_verification')),
    sa.UniqueConstraint('provider', 'provider_reference', name='uq_identity_verification_provider_reference')
    )
    op.create_index('ix_identity_verification_account_id', 'identity_verification', ['account_id'], unique=False)
    op.create_index('ix_identity_verification_stable_key', 'identity_verification', ['idv_stable_key'], unique=False)
    _require_empty_browser_session()
    op.add_column('browser_session', sa.Column('session_token_hash', sa.String(length=64), nullable=False))
    op.add_column('browser_session', sa.Column('revoke_reason', sa.String(length=40), nullable=True))
    op.add_column('browser_session', sa.Column('last_fresh_auth_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('browser_session', sa.Column('fresh_auth_assurance', sa.String(length=40), nullable=True))
    op.add_column('browser_session', sa.Column('created_ip', sa.String(length=45), nullable=True))
    op.add_column('browser_session', sa.Column('last_seen_ip', sa.String(length=45), nullable=True))
    op.create_unique_constraint('uq_browser_session_session_token_hash', 'browser_session', ['session_token_hash'])
    op.create_check_constraint(op.f('ck_browser_session_fresh_auth_assurance_valid'), 'browser_session', "fresh_auth_assurance IS NULL OR fresh_auth_assurance IN ('session', 'recent_verification', 'strong_otp', 'identity_verified')")
    op.create_check_constraint(op.f('ck_browser_session_fresh_auth_fields_all_or_none'), 'browser_session', '(last_fresh_auth_at IS NULL) = (fresh_auth_assurance IS NULL)')
    op.create_check_constraint(op.f('ck_browser_session_revoke_reason_matches_revoked_at'), 'browser_session', '(revoked_at IS NULL) = (revoke_reason IS NULL)')
    op.create_check_constraint(op.f('ck_browser_session_revoke_reason_valid'), 'browser_session', "revoke_reason IS NULL OR revoke_reason IN ('user_logout', 'user_logout_all', 'user_revoked_session', 'account_recovery', 'account_withdrawn', 'security_incident')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_browser_session_revoke_reason_valid'), 'browser_session', type_='check')
    op.drop_constraint(op.f('ck_browser_session_revoke_reason_matches_revoked_at'), 'browser_session', type_='check')
    op.drop_constraint(op.f('ck_browser_session_fresh_auth_fields_all_or_none'), 'browser_session', type_='check')
    op.drop_constraint(op.f('ck_browser_session_fresh_auth_assurance_valid'), 'browser_session', type_='check')
    op.drop_constraint('uq_browser_session_session_token_hash', 'browser_session', type_='unique')
    op.drop_column('browser_session', 'last_seen_ip')
    op.drop_column('browser_session', 'created_ip')
    op.drop_column('browser_session', 'fresh_auth_assurance')
    op.drop_column('browser_session', 'last_fresh_auth_at')
    op.drop_column('browser_session', 'revoke_reason')
    op.drop_column('browser_session', 'session_token_hash')
    op.drop_index('ix_identity_verification_stable_key', table_name='identity_verification')
    op.drop_index('ix_identity_verification_account_id', table_name='identity_verification')
    op.drop_table('identity_verification')
    op.drop_index('uq_auth_challenge_pending_target_purpose', table_name='auth_challenge', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_auth_challenge_expires_at', table_name='auth_challenge')
    op.drop_index('ix_auth_challenge_account_id', table_name='auth_challenge')
    op.drop_table('auth_challenge')
    # ### end Alembic commands ###
