"""customer db domain foundation

Revision ID: 36e752113d5e
Revises: 
Create Date: 2026-08-11 15:37:34.060521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '36e752113d5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idv_stable_key', sa.String(length=255), nullable=False),
    sa.Column('idv_provider', sa.String(length=64), nullable=False),
    sa.Column('idv_reference', sa.String(length=255), nullable=True),
    sa.Column('adult_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('adult_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adult_verified IS FALSE OR adult_verified_at IS NOT NULL', name=op.f('ck_person_identity_adult_verified_at_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_identity')),
    sa.UniqueConstraint('idv_stable_key', name='uq_person_identity_idv_stable_key')
    )
    op.create_table('plan_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('price_version', sa.Integer(), nullable=False),
    sa.Column('price_krw', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'KRW'"), nullable=False),
    sa.Column('vat_included', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('product_count', sa.SmallInteger(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(plan_code = 'package_two' AND product_count = 2) OR (plan_code = 'full_set' AND product_count = 3) OR (plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea') AND product_count = 1)", name=op.f('ck_plan_catalog_product_count_matches_plan')),
    sa.CheckConstraint("currency = 'KRW'", name=op.f('ck_plan_catalog_currency_krw')),
    sa.CheckConstraint("plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_plan_catalog_plan_code_valid')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_plan_catalog_effective_range')),
    sa.CheckConstraint('price_krw > 0', name=op.f('ck_plan_catalog_price_positive')),
    sa.CheckConstraint('price_version > 0', name=op.f('ck_plan_catalog_price_version_positive')),
    sa.CheckConstraint('vat_included IS TRUE', name=op.f('ck_plan_catalog_vat_included')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_catalog')),
    sa.UniqueConstraint('plan_code', 'price_version', name='uq_plan_catalog_plan_code_price_version')
    )
    op.create_index('uq_plan_catalog_open_plan_code', 'plan_catalog', ['plan_code'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_table('product',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('display_name_ko', sa.String(length=120), nullable=False),
    sa.Column('display_name_en', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code IN ('today_genie', 'keysuri_global', 'keysuri_korea')", name=op.f('ck_product_code_valid')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_product'))
    )
    op.create_table('trial_eligibility_block',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idv_stable_key', sa.String(length=255), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('block_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('block_expires_at > trial_ended_at', name=op.f('ck_trial_eligibility_block_expiry_after_end')),
    sa.CheckConstraint('trial_ended_at >= trial_started_at', name=op.f('ck_trial_eligibility_block_trial_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_eligibility_block')),
    sa.UniqueConstraint('idv_stable_key', name='uq_trial_eligibility_block_idv_stable_key')
    )
    op.create_index('ix_trial_eligibility_block_block_expires_at', 'trial_eligibility_block', ['block_expires_at'], unique=False)
    op.create_table('customer_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('mobile_e164', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_email = lower(account_email) AND position('@' in account_email) > 1", name=op.f('ck_customer_account_email_normalized')),
    sa.CheckConstraint("mobile_e164 IS NULL OR mobile_e164 ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f('ck_customer_account_mobile_e164_format')),
    sa.CheckConstraint("status <> 'withdrawn' OR withdrawn_at IS NOT NULL", name=op.f('ck_customer_account_withdrawn_at_present')),
    sa.CheckConstraint("status IN ('active', 'withdrawn')", name=op.f('ck_customer_account_status_valid')),
    sa.ForeignKeyConstraint(['person_id'], ['person_identity.id'], name=op.f('fk_customer_account_person_id_person_identity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_account'))
    )
    op.create_index('uq_customer_account_active_email', 'customer_account', ['account_email'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_customer_account_active_person', 'customer_account', ['person_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('plan_fixed_product',
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.CheckConstraint("plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'full_set')", name=op.f('ck_plan_fixed_product_plan_code_is_fixed_membership')),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], name=op.f('fk_plan_fixed_product_product_code_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plan_code', 'product_code', name=op.f('pk_plan_fixed_product'))
    )
    op.create_table('browser_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('remember_login', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactivity_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('inactivity_expires_at <= absolute_expires_at', name=op.f('ck_browser_session_expiry_ordering')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_browser_session_account_id_customer_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_browser_session'))
    )
    op.create_index('ix_browser_session_account_id', 'browser_session', ['account_id'], unique=False)
    op.create_table('command_idempotency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('command', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result_reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'completed' OR completed_at IS NOT NULL", name=op.f('ck_command_idempotency_completed_at_present')),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name=op.f('ck_command_idempotency_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_command_idempotency_account_id_customer_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_idempotency')),
    sa.UniqueConstraint('command', 'idempotency_key', name='uq_command_idempotency_command_key')
    )
    op.create_table('delivery_email',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppression_reason', sa.String(length=40), nullable=True),
    sa.Column('suppressed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'suppressed') = (suppression_reason IS NOT NULL)", name=op.f('ck_delivery_email_suppression_reason_matches_status')),
    sa.CheckConstraint("email = lower(email) AND position('@' in email) > 1", name=op.f('ck_delivery_email_normalized')),
    sa.CheckConstraint("status <> 'active' OR verified_at IS NOT NULL", name=op.f('ck_delivery_email_active_requires_verified')),
    sa.CheckConstraint("status <> 'suppressed' OR suppressed_at IS NOT NULL", name=op.f('ck_delivery_email_suppressed_at_present')),
    sa.CheckConstraint("status IN ('pending_verification', 'active', 'superseded', 'suppressed')", name=op.f('ck_delivery_email_status_valid')),
    sa.CheckConstraint("suppression_reason IS NULL OR suppression_reason IN ('hard_bounce', 'complaint', 'unsubscribe', 'operator_manual')", name=op.f('ck_delivery_email_suppression_reason_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_delivery_email_account_id_customer_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_email'))
    )
    op.create_index('ix_delivery_email_account_id', 'delivery_email', ['account_id'], unique=False)
    op.create_index('uq_delivery_email_active_account', 'delivery_email', ['account_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_delivery_email_pending_account', 'delivery_email', ['account_id'], unique=True, postgresql_where=sa.text("status = 'pending_verification'"))
    op.create_table('payment_method',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('billing_key_reference', sa.String(length=255), nullable=False),
    sa.Column('card_brand', sa.String(length=40), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('display_label', sa.String(length=120), nullable=True),
    sa.Column('own_name_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('own_name_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('own_name_verification_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("card_last4 IS NULL OR card_last4 ~ '^[0-9]{4}$'", name=op.f('ck_payment_method_card_last4_format')),
    sa.CheckConstraint("is_default IS FALSE OR status = 'active'", name=op.f('ck_payment_method_default_must_be_active')),
    sa.CheckConstraint("status <> 'revoked' OR revoked_at IS NOT NULL", name=op.f('ck_payment_method_revoked_at_present')),
    sa.CheckConstraint("status IN ('active', 'revoked', 'invalid')", name=op.f('ck_payment_method_status_valid')),
    sa.CheckConstraint('own_name_verified IS FALSE OR own_name_verified_at IS NOT NULL', name=op.f('ck_payment_method_own_name_verified_at_present')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_payment_method_account_id_customer_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_method')),
    sa.UniqueConstraint('provider', 'billing_key_reference', name='uq_payment_method_provider_billing_key_reference')
    )
    op.create_index('ix_payment_method_account_id', 'payment_method', ['account_id'], unique=False)
    op.create_index('uq_payment_method_default_account', 'payment_method', ['account_id'], unique=True, postgresql_where=sa.text('is_default IS TRUE'))
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('trial_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_start_date', sa.Date(), nullable=False),
    sa.Column('first_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contracted_plan_code', sa.String(length=40), nullable=True),
    sa.Column('contracted_price_krw', sa.Integer(), nullable=True),
    sa.Column('contracted_price_version', sa.Integer(), nullable=True),
    sa.Column('contracted_currency', sa.String(length=3), nullable=True),
    sa.Column('contracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_anchor_day', sa.SmallInteger(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contracted_currency IS NULL OR contracted_currency = 'KRW'", name=op.f('ck_subscription_contracted_currency_krw')),
    sa.CheckConstraint("contracted_plan_code IS NULL OR contracted_plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_subscription_contracted_plan_code_valid')),
    sa.CheckConstraint("state <> 'cancellation_scheduled' OR cancellation_effective_at IS NOT NULL", name=op.f('ck_subscription_cancellation_scheduled_has_effective_at')),
    sa.CheckConstraint("state <> 'trial_expired' OR contracted_plan_code IS NULL", name=op.f('ck_subscription_trial_expired_never_paid')),
    sa.CheckConstraint("state <> 'withdrawal_scheduled' OR withdrawal_effective_at IS NOT NULL", name=op.f('ck_subscription_withdrawal_scheduled_has_effective_at')),
    sa.CheckConstraint("state IN ('trialing', 'renewal_pending', 'conversion_scheduled', 'trial_expired', 'active', 'past_due', 'suspended', 'cancellation_scheduled', 'canceled', 'withdrawal_scheduled', 'withdrawn')", name=op.f('ck_subscription_state_valid')),
    sa.CheckConstraint("state NOT IN ('active', 'past_due', 'suspended', 'cancellation_scheduled', 'withdrawal_scheduled') OR (contracted_plan_code IS NOT NULL AND billing_anchor_day IS NOT NULL)", name=op.f('ck_subscription_paid_states_require_contract')),
    sa.CheckConstraint("state NOT IN ('trial_expired', 'canceled', 'withdrawn') OR ended_at IS NOT NULL", name=op.f('ck_subscription_terminal_states_have_ended_at')),
    sa.CheckConstraint("state NOT IN ('trialing', 'renewal_pending', 'conversion_scheduled') OR contracted_plan_code IS NULL", name=op.f('ck_subscription_no_paid_plan_during_trial')),
    sa.CheckConstraint("state NOT IN ('trialing', 'renewal_pending', 'conversion_scheduled') OR trial_start_at IS NOT NULL", name=op.f('ck_subscription_trial_states_require_trial_bounds')),
    sa.CheckConstraint('(contracted_plan_code IS NULL AND contracted_price_krw IS NULL  AND contracted_price_version IS NULL AND contracted_currency IS NULL  AND contracted_at IS NULL) OR (contracted_plan_code IS NOT NULL AND contracted_price_krw IS NOT NULL  AND contracted_price_version IS NOT NULL  AND contracted_currency IS NOT NULL AND contracted_at IS NOT NULL)', name=op.f('ck_subscription_contract_fields_all_or_none')),
    sa.CheckConstraint('(trial_start_at IS NULL) = (trial_end_at IS NULL)', name=op.f('ck_subscription_trial_bounds_all_or_none')),
    sa.CheckConstraint('billing_anchor_day IS NULL OR (billing_anchor_day >= 1 AND billing_anchor_day <= 31)', name=op.f('ck_subscription_billing_anchor_day_range')),
    sa.CheckConstraint('contracted_price_krw IS NULL OR contracted_price_krw > 0', name=op.f('ck_subscription_contracted_price_positive')),
    sa.CheckConstraint('current_period_end IS NULL OR current_period_start IS NULL OR current_period_end > current_period_start', name=op.f('ck_subscription_period_range')),
    sa.CheckConstraint('trial_end_at IS NULL OR trial_end_at > trial_start_at', name=op.f('ck_subscription_trial_range')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_subscription_account_id_customer_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contracted_plan_code', 'contracted_price_version'], ['plan_catalog.plan_code', 'plan_catalog.price_version'], name='fk_subscription_contracted_plan_catalog', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    op.create_index('ix_subscription_next_billing_at', 'subscription', ['next_billing_at'], unique=False)
    op.create_index('ix_subscription_trial_end_at', 'subscription', ['trial_end_at'], unique=False)
    op.create_index('uq_subscription_active_account', 'subscription', ['account_id'], unique=True, postgresql_where=sa.text("state NOT IN ('trial_expired', 'canceled', 'withdrawn')"))
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('actor_account_id', sa.Uuid(), nullable=True),
    sa.Column('actor_operator_reference', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("actor_type <> 'customer' OR actor_account_id IS NOT NULL", name=op.f('ck_audit_event_customer_actor_has_account')),
    sa.CheckConstraint("actor_type <> 'operator' OR actor_operator_reference IS NOT NULL", name=op.f('ck_audit_event_operator_actor_has_reference')),
    sa.CheckConstraint("actor_type IN ('customer', 'system', 'operator')", name=op.f('ck_audit_event_actor_type_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_audit_event_account_id_customer_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_account_id'], ['customer_account.id'], name=op.f('fk_audit_event_actor_account_id_customer_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_audit_event_subscription_id_subscription'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index('ix_audit_event_account_id_occurred_at', 'audit_event', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_event_event_type_occurred_at', 'audit_event', ['event_type', 'occurred_at'], unique=False)
    op.create_table('conversion_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('price_krw', sa.Integer(), nullable=False),
    sa.Column('price_version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'KRW'"), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'KRW'", name=op.f('ck_conversion_snapshot_currency_krw')),
    sa.CheckConstraint("plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_conversion_snapshot_plan_code_valid')),
    sa.CheckConstraint("status <> 'applied' OR applied_at IS NOT NULL", name=op.f('ck_conversion_snapshot_applied_at_present')),
    sa.CheckConstraint("status IN ('pending', 'applied', 'abandoned')", name=op.f('ck_conversion_snapshot_status_valid')),
    sa.CheckConstraint('price_krw > 0', name=op.f('ck_conversion_snapshot_price_positive')),
    sa.ForeignKeyConstraint(['plan_code', 'price_version'], ['plan_catalog.plan_code', 'plan_catalog.price_version'], name='fk_conversion_snapshot_plan_catalog', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_conversion_snapshot_subscription_id_subscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_snapshot'))
    )
    op.create_index('uq_conversion_snapshot_pending_subscription', 'conversion_snapshot', ['subscription_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('entitlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=True),
    sa.Column('price_version', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source = 'trial' AND plan_code IS NULL AND price_version IS NULL) OR (source = 'paid' AND plan_code IS NOT NULL AND price_version IS NOT NULL)", name=op.f('ck_entitlement_plan_matches_source')),
    sa.CheckConstraint("plan_code IS NULL OR plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_entitlement_plan_code_valid')),
    sa.CheckConstraint("source IN ('trial', 'paid')", name=op.f('ck_entitlement_source_valid')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_entitlement_effective_range')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_entitlement_account_id_customer_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], name=op.f('fk_entitlement_product_code_product'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_entitlement_subscription_id_subscription'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement'))
    )
    op.create_index('ix_entitlement_account_product_effective_from', 'entitlement', ['account_id', 'product_code', 'effective_from'], unique=False)
    op.create_index('uq_entitlement_open_subscription_product', 'entitlement', ['subscription_id', 'product_code'], unique=True, postgresql_where=sa.text('revoked_at IS NULL AND effective_to IS NULL'))
    op.create_table('subscription_product',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], name=op.f('fk_subscription_product_product_code_product'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_subscription_product_subscription_id_subscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', 'product_code', name=op.f('pk_subscription_product'))
    )
    op.create_table('billing_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('conversion_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('retry_offset_day', sa.SmallInteger(), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('amount_krw', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'KRW'"), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('price_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'KRW'", name=op.f('ck_billing_attempt_currency_krw')),
    sa.CheckConstraint("plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_billing_attempt_plan_code_valid')),
    sa.CheckConstraint("purpose <> 'first_conversion_charge' OR conversion_snapshot_id IS NOT NULL", name=op.f('ck_billing_attempt_first_charge_requires_snapshot')),
    sa.CheckConstraint("purpose IN ('first_conversion_charge', 'renewal_charge', 'recovery_charge')", name=op.f('ck_billing_attempt_purpose_valid')),
    sa.CheckConstraint("status <> 'failed' OR failure_code IS NOT NULL", name=op.f('ck_billing_attempt_failed_requires_code')),
    sa.CheckConstraint("status <> 'succeeded' OR (settled_at IS NOT NULL AND provider_transaction_reference IS NOT NULL)", name=op.f('ck_billing_attempt_succeeded_requires_settlement')),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed', 'provider_state_unknown', 'abandoned')", name=op.f('ck_billing_attempt_status_valid')),
    sa.CheckConstraint('amount_krw > 0', name=op.f('ck_billing_attempt_amount_positive')),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_billing_attempt_attempt_no_positive')),
    sa.CheckConstraint('billing_period_end > billing_period_start', name=op.f('ck_billing_attempt_period_range')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_billing_attempt_account_id_customer_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversion_snapshot_id'], ['conversion_snapshot.id'], name=op.f('fk_billing_attempt_conversion_snapshot_id_conversion_snapshot'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], name=op.f('fk_billing_attempt_payment_method_id_payment_method'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_billing_attempt_subscription_id_subscription'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_attempt')),
    sa.UniqueConstraint('idempotency_key', name='uq_billing_attempt_idempotency_key'),
    sa.UniqueConstraint('subscription_id', 'purpose', 'billing_period_start', 'attempt_no', name='uq_billing_attempt_subscription_purpose_period_attempt')
    )
    op.create_index('ix_billing_attempt_scheduled_at', 'billing_attempt', ['scheduled_at'], unique=False)
    op.create_index('ix_billing_attempt_subscription_id', 'billing_attempt', ['subscription_id'], unique=False)
    op.create_index('uq_billing_attempt_provider_transaction', 'billing_attempt', ['provider', 'provider_transaction_reference'], unique=True, postgresql_where=sa.text('provider_transaction_reference IS NOT NULL'))
    op.create_index('uq_billing_attempt_succeeded_period', 'billing_attempt', ['subscription_id', 'billing_period_start'], unique=True, postgresql_where=sa.text("status = 'succeeded'"))
    op.create_table('conversion_snapshot_product',
    sa.Column('conversion_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['conversion_snapshot_id'], ['conversion_snapshot.id'], name=op.f('fk_conversion_snapshot_product_conversion_snapshot_id_conversion_snapshot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], name=op.f('fk_conversion_snapshot_product_product_code_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('conversion_snapshot_id', 'product_code', name=op.f('pk_conversion_snapshot_product'))
    )
    op.create_table('recipient_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('delivery_email', sa.String(length=320), nullable=False),
    sa.Column('delivery_email_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_id', sa.Uuid(), nullable=False),
    sa.Column('entitlement_source', sa.String(length=40), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=True),
    sa.Column('price_version', sa.Integer(), nullable=True),
    sa.Column('subscription_state_at_snapshot', sa.String(length=40), nullable=False),
    sa.Column('billing_state_at_snapshot', sa.String(length=40), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delivery_email = lower(delivery_email) AND position('@' in delivery_email) > 1", name=op.f('ck_recipient_snapshot_delivery_email_normalized')),
    sa.CheckConstraint("entitlement_source IN ('trial', 'paid')", name=op.f('ck_recipient_snapshot_entitlement_source_valid')),
    sa.CheckConstraint("plan_code IS NULL OR plan_code IN ('today_genie', 'keysuri_global', 'keysuri_korea', 'package_two', 'full_set')", name=op.f('ck_recipient_snapshot_plan_code_valid')),
    sa.CheckConstraint("subscription_state_at_snapshot IN ('trialing', 'renewal_pending', 'conversion_scheduled', 'trial_expired', 'active', 'past_due', 'suspended', 'cancellation_scheduled', 'canceled', 'withdrawal_scheduled', 'withdrawn')", name=op.f('ck_recipient_snapshot_state_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['customer_account.id'], name=op.f('fk_recipient_snapshot_account_id_customer_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_email_id'], ['delivery_email.id'], name=op.f('fk_recipient_snapshot_delivery_email_id_delivery_email'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], name=op.f('fk_recipient_snapshot_entitlement_id_entitlement'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_code'], ['product.code'], name=op.f('fk_recipient_snapshot_product_code_product'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_recipient_snapshot_subscription_id_subscription'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipient_snapshot')),
    sa.UniqueConstraint('account_id', 'product_code', 'publication_date', name='uq_recipient_snapshot_account_product_publication_date')
    )
    op.create_index('ix_recipient_snapshot_publication_date_product', 'recipient_snapshot', ['publication_date', 'product_code'], unique=False)
    op.create_table('billing_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billing_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_event_reference', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_attempt_id'], ['billing_attempt.id'], name=op.f('fk_billing_event_billing_attempt_id_billing_attempt'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_event'))
    )
    op.create_index('ix_billing_event_billing_attempt_id_occurred_at', 'billing_event', ['billing_attempt_id', 'occurred_at'], unique=False)
    op.create_index('uq_billing_event_provider_event_reference', 'billing_event', ['provider_event_reference'], unique=True, postgresql_where=sa.text('provider_event_reference IS NOT NULL'))
    op.create_table('delivery_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_event_reference', sa.String(length=255), nullable=True),
    sa.Column('incident_key', sa.String(length=120), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('not_eligible', 'snapshot_frozen', 'send_attempted', 'provider_accepted', 'provider_rejected', 'soft_bounce', 'hard_bounce', 'complaint', 'delivered_evidence', 'unknown_after_submit', 'suppressed', 'customer_contact_failure', 'sender_incident')", name=op.f('ck_delivery_event_event_type_valid')),
    sa.ForeignKeyConstraint(['recipient_snapshot_id'], ['recipient_snapshot.id'], name=op.f('fk_delivery_event_recipient_snapshot_id_recipient_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_event'))
    )
    op.create_index('ix_delivery_event_snapshot_occurred_at', 'delivery_event', ['recipient_snapshot_id', 'occurred_at'], unique=False)
    op.create_index('uq_delivery_event_provider_event_reference', 'delivery_event', ['provider_event_reference'], unique=True, postgresql_where=sa.text('provider_event_reference IS NOT NULL'))
    # ### end Alembic commands ###

    _create_cardinality_triggers()
    _create_immutability_triggers()
    _seed_canonical_catalog()


def downgrade() -> None:
    _drop_immutability_triggers()
    _drop_cardinality_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_delivery_event_provider_event_reference', table_name='delivery_event', postgresql_where=sa.text('provider_event_reference IS NOT NULL'))
    op.drop_index('ix_delivery_event_snapshot_occurred_at', table_name='delivery_event')
    op.drop_table('delivery_event')
    op.drop_index('uq_billing_event_provider_event_reference', table_name='billing_event', postgresql_where=sa.text('provider_event_reference IS NOT NULL'))
    op.drop_index('ix_billing_event_billing_attempt_id_occurred_at', table_name='billing_event')
    op.drop_table('billing_event')
    op.drop_index('ix_recipient_snapshot_publication_date_product', table_name='recipient_snapshot')
    op.drop_table('recipient_snapshot')
    op.drop_table('conversion_snapshot_product')
    op.drop_index('uq_billing_attempt_succeeded_period', table_name='billing_attempt', postgresql_where=sa.text("status = 'succeeded'"))
    op.drop_index('uq_billing_attempt_provider_transaction', table_name='billing_attempt', postgresql_where=sa.text('provider_transaction_reference IS NOT NULL'))
    op.drop_index('ix_billing_attempt_subscription_id', table_name='billing_attempt')
    op.drop_index('ix_billing_attempt_scheduled_at', table_name='billing_attempt')
    op.drop_table('billing_attempt')
    op.drop_table('subscription_product')
    op.drop_index('uq_entitlement_open_subscription_product', table_name='entitlement', postgresql_where=sa.text('revoked_at IS NULL AND effective_to IS NULL'))
    op.drop_index('ix_entitlement_account_product_effective_from', table_name='entitlement')
    op.drop_table('entitlement')
    op.drop_index('uq_conversion_snapshot_pending_subscription', table_name='conversion_snapshot', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('conversion_snapshot')
    op.drop_index('ix_audit_event_event_type_occurred_at', table_name='audit_event')
    op.drop_index('ix_audit_event_account_id_occurred_at', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('uq_subscription_active_account', table_name='subscription', postgresql_where=sa.text("state NOT IN ('trial_expired', 'canceled', 'withdrawn')"))
    op.drop_index('ix_subscription_trial_end_at', table_name='subscription')
    op.drop_index('ix_subscription_next_billing_at', table_name='subscription')
    op.drop_table('subscription')
    op.drop_index('uq_payment_method_default_account', table_name='payment_method', postgresql_where=sa.text('is_default IS TRUE'))
    op.drop_index('ix_payment_method_account_id', table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index('uq_delivery_email_pending_account', table_name='delivery_email', postgresql_where=sa.text("status = 'pending_verification'"))
    op.drop_index('uq_delivery_email_active_account', table_name='delivery_email', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_delivery_email_account_id', table_name='delivery_email')
    op.drop_table('delivery_email')
    op.drop_table('command_idempotency')
    op.drop_index('ix_browser_session_account_id', table_name='browser_session')
    op.drop_table('browser_session')
    op.drop_table('plan_fixed_product')
    op.drop_index('uq_customer_account_active_person', table_name='customer_account', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_customer_account_active_email', table_name='customer_account', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('customer_account')
    op.drop_index('ix_trial_eligibility_block_block_expires_at', table_name='trial_eligibility_block')
    op.drop_table('trial_eligibility_block')
    op.drop_table('product')
    op.drop_index('uq_plan_catalog_open_plan_code', table_name='plan_catalog', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_table('plan_catalog')
    op.drop_table('person_identity')
    # ### end Alembic commands ###


# ---------------------------------------------------------------------------
# Plan product-set cardinality
#
# "package_two contains exactly two distinct products" is a cross-row rule, so
# no CHECK constraint can express it. DEFERRABLE INITIALLY DEFERRED constraint
# triggers are used instead: a transaction may insert the parent and its
# product rows in any order, and the count is validated once at COMMIT.
#
# Enforcing this in the database rather than only in a future service layer is
# deliberate - a mis-sized package_two would mean charging one price and
# delivering a different product set.
# ---------------------------------------------------------------------------

_SUBSCRIPTION_PRODUCT_CARDINALITY_FN = """
CREATE OR REPLACE FUNCTION customer_check_subscription_product_cardinality()
RETURNS TRIGGER AS $$
DECLARE
    target_subscription_id uuid;
    expected_count smallint;
    actual_count smallint;
    target_plan_code varchar(40);
BEGIN
    -- Fired from two relations: `subscription_product` (child rows carry
    -- subscription_id) and `subscription` itself (the parent's own id).
    IF TG_OP = 'DELETE' THEN
        target_subscription_id := OLD.subscription_id;
    ELSIF TG_TABLE_NAME = 'subscription' THEN
        target_subscription_id := NEW.id;
    ELSE
        target_subscription_id := NEW.subscription_id;
    END IF;

    SELECT s.contracted_plan_code INTO target_plan_code
    FROM subscription s WHERE s.id = target_subscription_id;

    -- Subscription gone (cascade delete), or still trialing with no paid
    -- contract: there is nothing to size the product set against.
    IF NOT FOUND OR target_plan_code IS NULL THEN
        RETURN NULL;
    END IF;

    expected_count := CASE
        WHEN target_plan_code = 'full_set' THEN 3
        WHEN target_plan_code = 'package_two' THEN 2
        ELSE 1
    END;

    SELECT count(DISTINCT sp.product_code) INTO actual_count
    FROM subscription_product sp
    WHERE sp.subscription_id = target_subscription_id;

    IF actual_count <> expected_count THEN
        RAISE EXCEPTION
            'subscription % plan % requires exactly % product(s), found %',
            target_subscription_id, target_plan_code, expected_count, actual_count
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""

_CONVERSION_SNAPSHOT_PRODUCT_CARDINALITY_FN = """
CREATE OR REPLACE FUNCTION customer_check_conversion_snapshot_cardinality()
RETURNS TRIGGER AS $$
DECLARE
    target_snapshot_id uuid;
    expected_count smallint;
    actual_count smallint;
    target_plan_code varchar(40);
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_snapshot_id := OLD.conversion_snapshot_id;
    ELSIF TG_TABLE_NAME = 'conversion_snapshot' THEN
        target_snapshot_id := NEW.id;
    ELSE
        target_snapshot_id := NEW.conversion_snapshot_id;
    END IF;

    SELECT cs.plan_code INTO target_plan_code
    FROM conversion_snapshot cs WHERE cs.id = target_snapshot_id;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    expected_count := CASE
        WHEN target_plan_code = 'full_set' THEN 3
        WHEN target_plan_code = 'package_two' THEN 2
        ELSE 1
    END;

    SELECT count(DISTINCT csp.product_code) INTO actual_count
    FROM conversion_snapshot_product csp
    WHERE csp.conversion_snapshot_id = target_snapshot_id;

    IF actual_count <> expected_count THEN
        RAISE EXCEPTION
            'conversion snapshot % plan % requires exactly % product(s), found %',
            target_snapshot_id, target_plan_code, expected_count, actual_count
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


def _create_cardinality_triggers() -> None:
    op.execute(_SUBSCRIPTION_PRODUCT_CARDINALITY_FN)
    op.execute(_CONVERSION_SNAPSHOT_PRODUCT_CARDINALITY_FN)

    op.execute(
        """
        CREATE CONSTRAINT TRIGGER subscription_product_cardinality
        AFTER INSERT OR UPDATE OR DELETE ON subscription_product
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION customer_check_subscription_product_cardinality();
        """
    )
    # Also fires when a subscription gains or changes a paid contract, so an
    # `active` subscription can never exist with an empty product set.
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER subscription_contract_product_cardinality
        AFTER INSERT OR UPDATE OF contracted_plan_code ON subscription
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        WHEN (NEW.contracted_plan_code IS NOT NULL)
        EXECUTE FUNCTION customer_check_subscription_product_cardinality();
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER conversion_snapshot_product_cardinality
        AFTER INSERT OR UPDATE OR DELETE ON conversion_snapshot_product
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION customer_check_conversion_snapshot_cardinality();
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER conversion_snapshot_cardinality
        AFTER INSERT OR UPDATE OF plan_code ON conversion_snapshot
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION customer_check_conversion_snapshot_cardinality();
        """
    )


def _drop_cardinality_triggers() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS conversion_snapshot_cardinality "
        "ON conversion_snapshot;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS conversion_snapshot_product_cardinality "
        "ON conversion_snapshot_product;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS subscription_contract_product_cardinality "
        "ON subscription;"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS subscription_product_cardinality "
        "ON subscription_product;"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS customer_check_conversion_snapshot_cardinality();"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS customer_check_subscription_product_cardinality();"
    )


# ---------------------------------------------------------------------------
# Immutability
#
# Delivery contract sec. 7: changes after a recipient snapshot is frozen apply
# to the NEXT snapshot, never to the frozen one. Audit records are likewise
# append-only. DELETE is intentionally left permitted on both, because
# retention and statutory-erasure jobs need it; only in-place rewriting is
# blocked.
# ---------------------------------------------------------------------------

_FORBID_UPDATE_FN = """
CREATE OR REPLACE FUNCTION customer_forbid_update()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'relation % is append-only; rows may not be updated in place',
        TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
"""


def _create_immutability_triggers() -> None:
    op.execute(_FORBID_UPDATE_FN)
    op.execute(
        """
        CREATE TRIGGER recipient_snapshot_immutable
        BEFORE UPDATE ON recipient_snapshot
        FOR EACH ROW EXECUTE FUNCTION customer_forbid_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_event_immutable
        BEFORE UPDATE ON audit_event
        FOR EACH ROW EXECUTE FUNCTION customer_forbid_update();
        """
    )


def _drop_immutability_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_immutable ON audit_event;")
    op.execute(
        "DROP TRIGGER IF EXISTS recipient_snapshot_immutable ON recipient_snapshot;"
    )
    op.execute("DROP FUNCTION IF EXISTS customer_forbid_update();")


# ---------------------------------------------------------------------------
# Canonical catalog seed
#
# Source: docs/web/CUSTOMER_LIFECYCLE_BILLING_POLICY_v1.md sec. 1, corroborated
# by docs/BUSINESS_BRAND_SSOT_v1.md sec. 7.
#
# Full Set is 16,500 KRW (supply 15,000 + VAT 1,500), set by explicit owner
# decision. The earlier 14,300 KRW figure is HISTORICAL and MUST NOT be seeded.
# This migration has never been deployed, so the correction is applied to the
# initial foundation rather than by fabricating a price_version 2.
#
# Seeded here rather than at application start-up because these codes and the
# price_version they anchor are referenced by foreign keys from every paid
# contract; an empty catalog would make the schema unusable.
# ---------------------------------------------------------------------------

_PRODUCTS = (
    ("today_genie", "오늘의 지니 브리핑", "Today Genie Briefing"),
    ("keysuri_global", "키수리 글로벌", "KeeSuri Global"),
    ("keysuri_korea", "키수리 코리아", "KeeSuri Korea"),
)

# (plan_code, price_krw VAT-inclusive, product_count)
_PLANS = (
    ("today_genie", 6600, 1),
    ("keysuri_global", 9900, 1),
    ("keysuri_korea", 6600, 1),
    ("package_two", 11000, 2),
    ("full_set", 16500, 3),
)

# package_two is absent: its two products are a customer selection, not a
# catalog fact.
_PLAN_FIXED_PRODUCTS = (
    ("today_genie", "today_genie"),
    ("keysuri_global", "keysuri_global"),
    ("keysuri_korea", "keysuri_korea"),
    ("full_set", "today_genie"),
    ("full_set", "keysuri_global"),
    ("full_set", "keysuri_korea"),
)

INITIAL_PRICE_VERSION = 1


def _seed_canonical_catalog() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.text(
            "INSERT INTO product (code, display_name_ko, display_name_en) "
            "VALUES (:code, :ko, :en)"
        ),
        [{"code": c, "ko": ko, "en": en} for c, ko, en in _PRODUCTS],
    )

    connection.execute(
        sa.text(
            "INSERT INTO plan_catalog "
            "(id, plan_code, price_version, price_krw, currency, vat_included, "
            " product_count, effective_from) "
            "VALUES (gen_random_uuid(), :plan_code, :price_version, :price_krw, "
            "        'KRW', TRUE, :product_count, now())"
        ),
        [
            {
                "plan_code": plan_code,
                "price_version": INITIAL_PRICE_VERSION,
                "price_krw": price_krw,
                "product_count": product_count,
            }
            for plan_code, price_krw, product_count in _PLANS
        ],
    )

    connection.execute(
        sa.text(
            "INSERT INTO plan_fixed_product (plan_code, product_code) "
            "VALUES (:plan_code, :product_code)"
        ),
        [
            {"plan_code": plan_code, "product_code": product_code}
            for plan_code, product_code in _PLAN_FIXED_PRODUCTS
        ],
    )
